#!/usr/bin/env python3
"""Rewrite implementation details and unnecessary claims out of the copies here.

The SDK monorepo keeps its internal notes; sync-from-monorepo.sh runs this over
the copies in this repo so the headers describe the API without naming what is
behind it.

Substitutions apply to COMMENT TEXT ONLY -- identifiers such as
VIDEOSDK_FFI_H, vsdk_meeting_on_video and videosdk_audio_player_trampoline are
code and must not change, or the headers stop compiling.

Usage: scrub.py <dir> [<dir>...]
Exits non-zero if a term survives, which means the table below needs a new
entry: a header gained wording this does not know about.
"""
import pathlib
import re
import sys

# Longest first: "libwebrtc's FrameCryptor" must win over "libwebrtc".
SUBS = [
    # Claims that say nothing a reader can act on.
    ("Audio/video console — one source for every platform, no device code.",
     "Audio/video console example."),
    ("AUTO-GENERATED by cbindgen", "AUTO-GENERATED"),
    ("Generated by cbindgen", "Generated"),
    ("libwebrtc's underlying FrameCryptor", "The underlying frame encryption"),
    ("current libwebrtc backend", "current backend"),
    ("with\n/// libwebrtc the decode", "with\n/// the media engine the decode"),
    ("libwebrtc decodes; NetEq smooths jitter", "Decoding and jitter smoothing are built in"),
    ("libwebrtc the decode happens inside Rust", "this backend the decode happens inside the SDK"),
    ("libwebrtc's FrameCryptor", "the frame encryption"),
    ("FrameCryptor", "frame encryption"),
    ("libwebrtc-backed", "current"),
    ("libwebrtc", "the media engine"),
    ("the Rust core", "the SDK core"),
    ("Rust core", "SDK core"),
    ("Rust-side", "inside the SDK"),
    ("inside Rust", "inside the SDK"),
    ("Rust worker thread", "SDK worker thread"),
    ("Rust", "SDK"),  # catch-all: comments wrap, so "the Rust\ncore" happens
    ("the SFU", "the media server"),
    ("SFU", "media server"),
    ("FFI boundary", "C ABI boundary"),
    ("direct-FFI", "direct C ABI"),
    ("direct FFI", "direct C ABI"),
    ("trampoline", "bridge"),
    ("APM/encoder", "processing/encoder"),
    ("APM", "audio processing"),
    ("NetEq", "the jitter buffer"),
    ("mediasoup", "the media server"),
]

# Anything still matching these in comment text is an unhandled leak.
LEAKS = re.compile(r"\b(libwebrtc|Rust|SFU|cbindgen|trampoline|FrameCryptor|NetEq|mediasoup)\b")

COMMENT = re.compile(r"(//|/\*|^\s*\*(?!/))")


def split_comment(line):
    """Return (code_part, comment_part). Naive but safe for these headers:
    none of them put // or /* inside a string literal."""
    m = COMMENT.search(line)
    if not m:
        return line, ""
    return line[: m.start()], line[m.start() :]


def main():
    roots = [pathlib.Path(a) for a in sys.argv[1:]]
    changed, leaks = 0, []
    for root in roots:
      for path in sorted(root.rglob("*")):
        if path.suffix not in (".h", ".hpp", ".cpp") or path.name == "videosdk_ffi.h":
            continue
        out, hit = [], False
        for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            code, comment = split_comment(line)
            if comment:
                new = comment
                for a, b in SUBS:
                    new = new.replace(a, b)
                if new != comment:
                    hit = True
                comment = new
                if LEAKS.search(comment):
                    leaks.append(f"{path}:{n}: {comment.strip()}")
            out.append(code + comment)
        if hit:
            changed += 1
            path.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"scrubbed {changed} file(s)")
    if leaks:
        print("\nerror: wording this script does not know about:", file=sys.stderr)
        for l in leaks:
            print("  " + l, file=sys.stderr)
        print("\nAdd an entry to SUBS in scripts/scrub.py.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
