/* AUTO-GENERATED by cbindgen — DO NOT EDIT BY HAND. */

#ifndef VIDEOSDK_FFI_H
#define VIDEOSDK_FFI_H

#pragma once

/* Generated by cbindgen — DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

// E2EE algorithm selector matching the `videosdk-e2ee` crate's Vsdk family.
//
// libwebrtc's underlying FrameCryptor uses a single `AesGcm` mode; the
// 128-vs-256 distinction is a key-material length hint documented for
// wire-format compatibility with iOS / Flutter / Android. The MVP maps both
// values to AES-GCM inside libwebrtc — the enum exists so the wire format
// stays selectable when we later add 256-bit key derivation.
typedef enum VsdkE2eeAlgorithm {
  // Vsdk AES-GCM 128 — default; interops with mobile SDKs' default.
  VSDK_E2EE_ALGORITHM_VSDK_AES_GCM128 = 0,
  // Vsdk AES-GCM 256 — same wire framing, 256-bit derived key.
  VSDK_E2EE_ALGORITHM_VSDK_AES_GCM256 = 1,
} VsdkE2eeAlgorithm;

// Error codes returned by `vsdk_*` functions.
typedef enum VsdkError {
  // Operation completed successfully.
  VSDK_ERROR_SUCCESS = 0,
  // Required config field was null or malformed.
  VSDK_ERROR_INVALID_CONFIG = 1,
  // One of the function arguments was null or invalid.
  VSDK_ERROR_INVALID_ARGUMENT = 2,
  // Failed to establish or maintain a connection to the SFU.
  VSDK_ERROR_CONNECTION_FAILED = 3,
  // Signaling protocol returned an error or violated the protocol.
  VSDK_ERROR_SIGNALING_FAILED = 4,
  // Call requires the session to be joined first.
  VSDK_ERROR_NOT_JOINED = 5,
  // Session is already joined.
  VSDK_ERROR_ALREADY_JOINED = 6,
  // Outbound send failed (e.g. transport closed).
  VSDK_ERROR_SEND_FAILED = 7,
  // Unexpected internal error. Check logs for details.
  VSDK_ERROR_INTERNAL_ERROR = 8,
  // A panic was caught at the FFI boundary.
  VSDK_ERROR_PANIC = 9,
} VsdkError;

// Opaque meeting handle.
typedef struct VsdkMeeting {
  uint8_t _private[0];
} VsdkMeeting;

// Initial configuration handed to `vsdk_meeting_create`.
typedef struct VsdkConfig {
  const char *meeting_id;
  const char *token;
  const char *name;
  const char *participant_id;
  const char *signaling_base_url;
  const char *device_info_json;
} VsdkConfig;

// One VP8 simulcast layer, supplied by the C++ side before join.
//
// Pass an array of 1–3 of these to `vsdk_meeting_set_simulcast_layers`,
// ordered smallest → largest. `width`/`height` are the layer's absolute
// target resolution; the SDK derives the per-layer downscale factor from the
// largest (top) layer. The top layer's resolution should equal the camera
// capture size. A bitrate/fps of 0 means "no explicit cap for this layer".
typedef struct VsdkSimulcastLayer {
  // Target encoded width in pixels.
  uint32_t width;
  // Target encoded height in pixels.
  uint32_t height;
  // Max bitrate for this layer, kilobits per second (0 = unset).
  uint32_t max_bitrate_kbps;
  // Max framerate for this layer (0 = unset).
  uint32_t max_fps;
  // Whether this layer is initially active (encoded + sent).
  bool active;
} VsdkSimulcastLayer;

// Fired when the backend advances the cloud-recording lifecycle:
// `RECORDING_STARTING` → `RECORDING_STARTED` → `RECORDING_STOPPING` →
// `RECORDING_STOPPED`. `status` is a NUL-terminated UTF-8 string valid only
// for the duration of the call.
typedef void (*VsdkOnRecordingState)(const char *status);

// Fired once when the backend confirms a recording has started or stopped.
// `payload_json` is the raw backend event serialized as NUL-terminated JSON
// (recording id, S3 path, etc.) — valid only for the duration of the call.
typedef void (*VsdkOnRecordingSimple)(const char *payload_json);

// Fired when the backend advances the HLS lifecycle:
// `HLS_STARTING` → `HLS_STARTED` → `HLS_STOPPING` → `HLS_STOPPED`.
// `status` is a NUL-terminated UTF-8 string valid only for the duration
// of the call.
typedef void (*VsdkOnHlsState)(const char *status);

// Fired once when the backend confirms an HLS session has started or
// stopped. `payload_json` is the raw backend event serialized as
// NUL-terminated JSON — valid only for the duration of the call.
typedef void (*VsdkOnHlsSimple)(const char *payload_json);

// Fired when the HLS session becomes playable — the backend has produced
// enough m3u8/TS segments for downstream players to attach. `payload_json`
// includes `playbackHlsUrl` and `livestreamUrl` fields. Hand the URL to
// any HLS-capable player (VLC, HLS.js, native iOS/Safari, etc.).
typedef void (*VsdkOnHlsPlayable)(const char *payload_json);

// Fired as the backend advances the RTMP livestream lifecycle:
// `LIVESTREAM_STARTING` → `LIVESTREAM_STARTED` → `LIVESTREAM_STOPPING`
// → `LIVESTREAM_STOPPED`. `status` is a NUL-terminated UTF-8 string
// valid only for the duration of the call.
typedef void (*VsdkOnLivestreamState)(const char *status);

// Fired once when the backend confirms an RTMP livestream has started
// or stopped. `payload_json` is the raw backend event serialized as
// NUL-terminated JSON — valid only for the duration of the call.
typedef void (*VsdkOnLivestreamSimple)(const char *payload_json);

// Decoded PCM audio frame delivered to the C++ side from libwebrtc.
//
// `samples` is interleaved 16-bit signed PCM, length
// `samples_per_channel * channels`. The pointer is valid only for the duration
// of the callback — copy out before returning.
typedef struct VsdkAudioFrame {
  const int16_t *samples;
  uint32_t samples_per_channel;
  uint32_t sample_rate;
  uint32_t channels;
  int64_t timestamp_us;
} VsdkAudioFrame;

// Fired when libwebrtc delivers a decoded PCM frame off a remote audio track.
typedef void (*VsdkOnAudioFrame)(const struct VsdkAudioFrame *frame);

// Decoded I420 video frame delivered to the C++ side from libwebrtc.
//
// The Y/U/V plane pointers and strides describe a standard I420 buffer
// (Y plane is `height * y_stride` bytes; U/V planes are
// `((height + 1) / 2) * stride` bytes each). Pointers are valid only for the
// duration of the callback.
typedef struct VsdkVideoFrame {
  const uint8_t *y;
  const uint8_t *u;
  const uint8_t *v;
  int32_t y_stride;
  int32_t u_stride;
  int32_t v_stride;
  uint32_t width;
  uint32_t height;
  int64_t timestamp_us;
  // Frame rotation in degrees (0, 90, 180, or 270).
  uint32_t rotation;
} VsdkVideoFrame;

// Fired when libwebrtc delivers a decoded I420 frame off a remote video track.
typedef void (*VsdkOnVideoFrame)(const struct VsdkVideoFrame *frame);

// Fired when a data-channel message is received. `data`/`len` are the RAW
// payload bytes (valid for the call only); `is_binary` mirrors the SCTP
// text/binary frame flag (false = UTF-8 text, true = arbitrary bytes).
typedef void (*VsdkOnDataMessage)(const uint8_t *data, uintptr_t len, bool is_binary);

// Fired when a new participant joins the room.
//
// `peer_id` and `name` are NUL-terminated UTF-8 strings valid for the duration
// of the call only.
typedef void (*VsdkOnParticipantJoined)(const char *peer_id, const char *name);

// Fired when a participant leaves the room.
typedef void (*VsdkOnParticipantLeft)(const char *peer_id);

// Fired when an unrecoverable error occurs after `vsdk_meeting_join`.
typedef void (*VsdkOnError)(enum VsdkError code, const char *message);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

 struct VsdkMeeting *vsdk_meeting_create(const struct VsdkConfig *config);

 enum VsdkError vsdk_meeting_join(struct VsdkMeeting *meeting);

 enum VsdkError vsdk_meeting_set_video_max_bitrate(struct VsdkMeeting *meeting, uint32_t kbps);

// Configure 1–3 VP8 simulcast layers for the outgoing camera video.
//
// Must be called BEFORE join. `layers` points to `count` `VsdkSimulcastLayer`
// entries ordered smallest → largest (1–3). Each layer's resolution, max
// bitrate, max framerate and active flag are honoured by the encoder. With a
// single layer this is equivalent to a plain single-stream produce at that
// resolution.

enum VsdkError vsdk_meeting_set_simulcast_layers(struct VsdkMeeting *meeting,
                                                 const struct VsdkSimulcastLayer *layers,
                                                 uintptr_t count);

 enum VsdkError vsdk_meeting_leave(struct VsdkMeeting *meeting);

// Stop publishing audio. Closes the microphone producer, so the other
// participants see the mic turn off. The next `vsdk_meeting_send_audio_pcm`
// publishes again. Call it after the last frame is sent; a frame racing it on
// another thread republishes. A no-op when no audio is published.
 enum VsdkError vsdk_meeting_disable_mic(struct VsdkMeeting *meeting);

// Stop publishing video. Closes the camera producer, so the other
// participants see the camera turn off. The next `vsdk_meeting_send_video_i420`
// publishes again. Call it after the last frame is sent; a frame racing it on
// another thread republishes. A no-op when no video is published.
 enum VsdkError vsdk_meeting_disable_webcam(struct VsdkMeeting *meeting);

 void vsdk_meeting_destroy(struct VsdkMeeting *meeting);


enum VsdkError vsdk_meeting_send_audio_pcm(struct VsdkMeeting *meeting,
                                           const int16_t *samples,
                                           uint32_t samples_per_channel,
                                           uint32_t sample_rate,
                                           uint32_t channels);


enum VsdkError vsdk_meeting_send_video_i420(struct VsdkMeeting *meeting,
                                            const uint8_t *y,
                                            const uint8_t *u,
                                            const uint8_t *v,
                                            uint32_t y_stride,
                                            uint32_t u_stride,
                                            uint32_t v_stride,
                                            uint32_t width,
                                            uint32_t height,
                                            int64_t timestamp_us);


enum VsdkError vsdk_meeting_send_data(struct VsdkMeeting *meeting,
                                      const uint8_t *data,
                                      uintptr_t len,
                                      bool is_binary);

// Start server-side recording. Every argument except the meeting handle is
// optional — pass `NULL` (or an empty string on the C++ side) to skip.
//
// * `webhook_url` — HTTPS URL the backend hits when recording state changes.
// * `aws_dir_path` — S3 destination path; when set, the backend uploads
//   the finished recording there instead of VideoSDK-managed storage.
// * `config_json` — JSON matching `videosdk::RecordingConfig`
//   (`layout`, `theme`, `mode`, `quality`, `orientation`).
// * `transcription_json` — JSON matching `videosdk::PostTranscriptionConfig`
//   (`enabled`, optional `summary`).

enum VsdkError vsdk_meeting_start_recording(struct VsdkMeeting *meeting,
                                            const char *webhook_url,
                                            const char *aws_dir_path,
                                            const char *config_json,
                                            const char *transcription_json);

// Stop the current recording. No-op on the backend side if no recording is
// active — check the state via `vsdk_meeting_on_recording_state_changed` if
// you need to gate the call.
 enum VsdkError vsdk_meeting_stop_recording(struct VsdkMeeting *meeting);

 void vsdk_meeting_on_recording_state_changed(struct VsdkMeeting *meeting, VsdkOnRecordingState cb);

 void vsdk_meeting_on_recording_started(struct VsdkMeeting *meeting, VsdkOnRecordingSimple cb);

 void vsdk_meeting_on_recording_stopped(struct VsdkMeeting *meeting, VsdkOnRecordingSimple cb);

// Start server-side HLS. Both arguments are optional — pass `NULL` to use
// backend defaults.
//
// * `config_json` — JSON matching `videosdk::HlsConfig` (structurally the
//   same as `RecordingConfig`: `layout`, `theme`, `mode`, `quality`,
//   `orientation`).
// * `transcription_json` — JSON matching `videosdk::PostTranscriptionConfig`.

enum VsdkError vsdk_meeting_start_hls(struct VsdkMeeting *meeting,
                                      const char *config_json,
                                      const char *transcription_json);

// Stop the current HLS session. Backend no-op if none is active — gate
// on `vsdk_meeting_on_hls_state_changed` if you need to check first.
 enum VsdkError vsdk_meeting_stop_hls(struct VsdkMeeting *meeting);

 void vsdk_meeting_on_hls_state_changed(struct VsdkMeeting *meeting, VsdkOnHlsState cb);

 void vsdk_meeting_on_hls_started(struct VsdkMeeting *meeting, VsdkOnHlsSimple cb);

 void vsdk_meeting_on_hls_stopped(struct VsdkMeeting *meeting, VsdkOnHlsSimple cb);

 void vsdk_meeting_on_hls_playable_state_changed(struct VsdkMeeting *meeting, VsdkOnHlsPlayable cb);

// Start server-side RTMP livestream.
//
// * `outputs_json` — REQUIRED. JSON array of `{url, streamKey}` objects
//   matching `videosdk::LivestreamOutput`. Field name on the wire is
//   `streamKey` (camelCase). Example:
//     `[{"url":"rtmp://a.rtmp.youtube.com/live2","streamKey":"xxxx-yyyy"}]`
//   Empty or malformed → `InvalidArgument`.
// * `config_json` — Optional generic JSON passed through to the backend.
//   Pass `NULL` (or empty string on the C++ side) to skip.

enum VsdkError vsdk_meeting_start_livestream(struct VsdkMeeting *meeting,
                                             const char *outputs_json,
                                             const char *config_json);

// Stop the current RTMP livestream. Backend no-op if none is active.
 enum VsdkError vsdk_meeting_stop_livestream(struct VsdkMeeting *meeting);


void vsdk_meeting_on_livestream_state_changed(struct VsdkMeeting *meeting,
                                              VsdkOnLivestreamState cb);

 void vsdk_meeting_on_livestream_started(struct VsdkMeeting *meeting, VsdkOnLivestreamSimple cb);

 void vsdk_meeting_on_livestream_stopped(struct VsdkMeeting *meeting, VsdkOnLivestreamSimple cb);

// Install (or replace) the E2EE shared key at index 0. `key`/`len` is a
// raw byte buffer — no C-string / UTF-8 coercion, so a random 32-byte key
// works. Passing `len == 0` returns `InvalidArgument`; use
// `vsdk_meeting_clear_e2ee` (via subsequent API additions) to disable.

enum VsdkError vsdk_meeting_set_e2ee_key(struct VsdkMeeting *meeting,
                                         const uint8_t *key,
                                         uintptr_t len);

// Advance the shared key one PBKDF2 ratchet step. Safe to call
// mid-meeting; peers auto-catch-up via `ratchet_window_size=16`. Returns
// `InvalidArgument` if E2EE hasn't been configured.
 enum VsdkError vsdk_meeting_ratchet_e2ee_key(struct VsdkMeeting *meeting);

// Select the AEAD algorithm. Advisory in the current libwebrtc-backed
// build (both variants map to AES-GCM in the underlying transformer); the
// enum exists to keep the C++ API shape aligned with iOS / Flutter /
// Android for future 256-bit key derivation.

enum VsdkError vsdk_meeting_set_e2ee_algorithm(struct VsdkMeeting *meeting,
                                               enum VsdkE2eeAlgorithm _algorithm);

 void vsdk_meeting_on_audio(struct VsdkMeeting *meeting, VsdkOnAudioFrame cb);

 void vsdk_meeting_on_video(struct VsdkMeeting *meeting, VsdkOnVideoFrame cb);

 void vsdk_meeting_on_data(struct VsdkMeeting *meeting, VsdkOnDataMessage cb);

 void vsdk_meeting_on_participant_joined(struct VsdkMeeting *meeting, VsdkOnParticipantJoined cb);

 void vsdk_meeting_on_participant_left(struct VsdkMeeting *meeting, VsdkOnParticipantLeft cb);

 void vsdk_meeting_on_error(struct VsdkMeeting *meeting, VsdkOnError cb);

// Start writing a Chrome trace to `path`. Returns `true` on success, `false`
// on argument or IO error. Idempotent — a second call while tracing is
// already active returns `true` without touching the file.
//
// # Safety
// `path` must be a NUL-terminated UTF-8 C string, or NULL (returns false).
 bool vsdk_trace_start(const char *path);

// Flush and close the trace file. No-op if no trace is active.
 void vsdk_trace_stop(void);

// Emit a Chrome instant event (a single tick-mark on the current thread's
// lane). `cat` and `name` are NUL-terminated UTF-8; either may be NULL
// (treated as empty string).
//
// # Safety
// Both pointers must be NUL-terminated UTF-8 C strings or NULL.
 void vsdk_trace_instant(const char *cat, const char *name);

// Begin a scope span. Returns a handle to pass to `vsdk_trace_scope_end`.
// When tracing is off the handle is `0`; passing `0` to `_end` is safe.
//
// # Safety
// Both pointers must be NUL-terminated UTF-8 C strings or NULL.
 uint64_t vsdk_trace_scope_begin(const char *cat, const char *name);

// End the scope identified by `handle`. No-op if the handle is 0 or unknown.
 void vsdk_trace_scope_end(uint64_t handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* VIDEOSDK_FFI_H */
